# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 322)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_add_name_c = QtWidgets.QLabel(self.centralwidget)
        self.lbl_add_name_c.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_add_name_c.setFont(font)
        self.lbl_add_name_c.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_name_c.setObjectName("lbl_add_name_c")
        self.lbl_add_num_c = QtWidgets.QLabel(self.centralwidget)
        self.lbl_add_num_c.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_add_num_c.setFont(font)
        self.lbl_add_num_c.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_num_c.setObjectName("lbl_add_num_c")
        self.lb_add_mail_c = QtWidgets.QLabel(self.centralwidget)
        self.lb_add_mail_c.setGeometry(QtCore.QRect(20, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_add_mail_c.setFont(font)
        self.lb_add_mail_c.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lb_add_mail_c.setObjectName("lb_add_mail_c")
        self.ledit_add_name_c = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_add_name_c.setGeometry(QtCore.QRect(100, 20, 131, 31))
        self.ledit_add_name_c.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                            "border-radius: 5px;")
        self.ledit_add_name_c.setObjectName("ledit_add_name_c")
        self.ledit_add_num_c = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_add_num_c.setGeometry(QtCore.QRect(100, 60, 131, 31))
        self.ledit_add_num_c.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                           "border-radius: 5px;")
        self.ledit_add_num_c.setObjectName("ledit_add_num_c")
        self.ledit_add_mail_c = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_add_mail_c.setGeometry(QtCore.QRect(100, 100, 131, 31))
        self.ledit_add_mail_c.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                            "border-radius: 5px;")
        self.ledit_add_mail_c.setObjectName("ledit_add_mail_c")
        self.btn_add_client = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_client.setGeometry(QtCore.QRect(70, 220, 111, 31))
        self.btn_add_client.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                          "color: rgb(75, 75, 75);\n"
                                          "font: 9pt \"Segoe UI\";\n"
                                          "border-radius: 5px;")
        self.btn_add_client.setObjectName("btn_add_client")
        self.lbl_add_adres = QtWidgets.QLabel(self.centralwidget)
        self.lbl_add_adres.setGeometry(QtCore.QRect(20, 140, 71, 21))
        self.lbl_add_adres.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_adres.setObjectName("lbl_add_adres")
        self.ledit_add_address = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_add_address.setGeometry(QtCore.QRect(100, 140, 131, 31))
        self.ledit_add_address.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                             "border-radius: 5px;")
        self.ledit_add_address.setObjectName("ledit_add_address")
        self.lbl_update_bdate = QtWidgets.QLabel(self.centralwidget)
        self.lbl_update_bdate.setGeometry(QtCore.QRect(390, 20, 111, 21))
        self.lbl_update_bdate.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_bdate.setObjectName("lbl_update_bdate")
        self.clndr_wdgt_add_date = QtWidgets.QCalendarWidget(self.centralwidget)
        self.clndr_wdgt_add_date.setGeometry(QtCore.QRect(290, 50, 351, 221))
        self.clndr_wdgt_add_date.setStyleSheet("")
        self.clndr_wdgt_add_date.setObjectName("clndr_wdgt_add_date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_add_name_c.setText(_translate("MainWindow", "Имя"))
        self.lbl_add_num_c.setText(_translate("MainWindow", "Номер"))
        self.lb_add_mail_c.setText(_translate("MainWindow", "Почта"))
        self.ledit_add_name_c.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.ledit_add_num_c.setPlaceholderText(_translate("MainWindow", "Введите номер"))
        self.ledit_add_mail_c.setPlaceholderText(_translate("MainWindow", "Введите почту"))
        self.btn_add_client.setText(_translate("MainWindow", "Добавить"))
        self.lbl_add_adres.setText(_translate("MainWindow", "Адрес"))
        self.ledit_add_address.setPlaceholderText(_translate("MainWindow", "Введите домашний адрес"))
        self.lbl_update_bdate.setText(_translate("MainWindow", "Дата рождения"))
