# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 493)
        MainWindow.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ledit_title = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_title.setGeometry(QtCore.QRect(170, 20, 151, 31))
        self.ledit_title.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                       "background-color: rgb(179, 179, 179);\n"
                                       "border-radius: 5px;")
        self.ledit_title.setObjectName("ledit_title")
        self.ledit_genre = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_genre.setGeometry(QtCore.QRect(170, 130, 151, 31))
        self.ledit_genre.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                       "background-color: rgb(179, 179, 179);\n"
                                       "border-radius: 5px;")
        self.ledit_genre.setObjectName("ledit_genre")
        self.ledit_author = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_author.setGeometry(QtCore.QRect(170, 230, 151, 31))
        self.ledit_author.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                        "background-color: rgb(179, 179, 179);\n"
                                        "border-radius: 5px;")
        self.ledit_author.setObjectName("ledit_author")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.lbl_title.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_genre = QtWidgets.QLabel(self.centralwidget)
        self.lbl_genre.setGeometry(QtCore.QRect(10, 70, 361, 31))
        self.lbl_genre.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
                                     "")
        self.lbl_genre.setObjectName("lbl_genre")
        self.lbl_author = QtWidgets.QLabel(self.centralwidget)
        self.lbl_author.setGeometry(QtCore.QRect(10, 180, 411, 31))
        self.lbl_author.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
                                      "")
        self.lbl_author.setObjectName("lbl_author")
        self.txt_edit_description = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_edit_description.setGeometry(QtCore.QRect(470, 50, 301, 151))
        self.txt_edit_description.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                "border-radius: 5px;")
        self.txt_edit_description.setObjectName("txt_edit_description")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 20, 111, 21))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(370, 370, 131, 31))
        self.btn_save.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                    "color: rgb(75, 75, 75);\n"
                                    "font: 9pt \"Segoe UI\";\n"
                                    "border-radius: 5px;")
        self.btn_save.setObjectName("btn_save")
        self.btn_load_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_img.setGeometry(QtCore.QRect(510, 230, 161, 31))
        self.btn_load_img.setStyleSheet("border-radius: 5px;\n"
                                        "background-color: rgb(0, 223, 223);\n"
                                        "color: rgb(75, 75, 75);\n"
                                        "font: 9pt \"Segoe UI\";\n"
                                        "")
        self.btn_load_img.setObjectName("btn_load_img")
        self.lbl_author_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_author_2.setGeometry(QtCore.QRect(20, 280, 111, 31))
        self.lbl_author_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lbl_author_2.setObjectName("lbl_author_2")
        self.ledit_year = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_year.setGeometry(QtCore.QRect(170, 280, 151, 31))
        self.ledit_year.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                      "background-color: rgb(179, 179, 179);\n"
                                      "border-radius: 5px;")
        self.ledit_year.setObjectName("ledit_year")
        self.btn_look_authors = QtWidgets.QPushButton(self.centralwidget)
        self.btn_look_authors.setGeometry(QtCore.QRect(10, 230, 141, 31))
        self.btn_look_authors.setStyleSheet("border-radius: 5px;\n"
                                            "background-color: rgb(0, 223, 223);\n"
                                            "color: rgb(75, 75, 75);\n"
                                            "font: 9pt \"Segoe UI\";\n"
                                            "")
        self.btn_look_authors.setObjectName("btn_look_authors")
        self.btn_look_genres = QtWidgets.QPushButton(self.centralwidget)
        self.btn_look_genres.setGeometry(QtCore.QRect(10, 130, 131, 31))
        self.btn_look_genres.setStyleSheet("border-radius: 5px;\n"
                                           "background-color: rgb(0, 223, 223);\n"
                                           "color: rgb(75, 75, 75);\n"
                                           "font: 9pt \"Segoe UI\";\n"
                                           "")
        self.btn_look_genres.setObjectName("btn_look_genres")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ledit_title.setPlaceholderText(_translate("MainWindow", "Введите название"))
        self.ledit_genre.setPlaceholderText(_translate("MainWindow", "Введите жанр"))
        self.ledit_author.setPlaceholderText(_translate("MainWindow", "Введите Фамилия И.О"))
        self.lbl_title.setText(_translate("MainWindow", "Название"))
        self.lbl_genre.setText(_translate("MainWindow", "Выберите жанр из списка или добавьте нового"))
        self.lbl_author.setText(_translate("MainWindow", "Выберите автора из списка или добавьте нового"))
        self.txt_edit_description.setPlaceholderText(_translate("MainWindow", "Краткое описание в двух словах"))
        self.label_5.setText(_translate("MainWindow", "Описание"))
        self.btn_save.setText(_translate("MainWindow", "Сохранить"))
        self.btn_load_img.setText(_translate("MainWindow", "Добавить обложку"))
        self.lbl_author_2.setText(_translate("MainWindow", "Год издания"))
        self.ledit_year.setPlaceholderText(_translate("MainWindow", "Введите год"))
        self.btn_look_authors.setText(_translate("MainWindow", "Выбрать автора"))
        self.btn_look_genres.setText(_translate("MainWindow", "Выбрать жанр"))
