# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 468)
        MainWindow.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 291, 41))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 101, 21))
        self.label_2.setObjectName("label_2")
        self.ledit__add_name_e2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit__add_name_e2.setGeometry(QtCore.QRect(180, 110, 131, 31))
        self.ledit__add_name_e2.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                              "background-color: rgb(179, 179, 179);\n"
                                              "border-radius: 5px;")
        self.ledit__add_name_e2.setObjectName("ledit__add_name_e2")
        self.ledit_add_number = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_add_number.setGeometry(QtCore.QRect(180, 160, 131, 31))
        self.ledit_add_number.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                            "background-color: rgb(179, 179, 179);\n"
                                            "border-radius: 5px;")
        self.ledit_add_number.setObjectName("ledit_add_number")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 55, 16))
        self.label_5.setObjectName("label_5")
        self.ledit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_pass.setGeometry(QtCore.QRect(180, 210, 131, 31))
        self.ledit_pass.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                      "background-color: rgb(179, 179, 179);\n"
                                      "border-radius: 5px;")
        self.ledit_pass.setObjectName("ledit_pass")
        self.btn_save_new_empl = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_new_empl.setGeometry(QtCore.QRect(190, 360, 121, 31))
        self.btn_save_new_empl.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                             "color: rgb(75, 75, 75);\n"
                                             "font: 9pt \"Segoe UI\";\n"
                                             "border-radius: 5px;")
        self.btn_save_new_empl.setObjectName("btn_save_new_empl")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.lbl_login.setObjectName("lbl_login")
        self.ledit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_login.setGeometry(QtCore.QRect(180, 60, 131, 31))
        self.ledit_login.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                       "background-color: rgb(179, 179, 179);\n"
                                       "border-radius: 5px;")
        self.ledit_login.setText("")
        self.ledit_login.setObjectName("ledit_login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Регистрация нового сотрудника"))
        self.label_2.setText(_translate("MainWindow", "Имя сотрудника"))
        self.ledit__add_name_e2.setPlaceholderText(_translate("MainWindow", "Фамилия И.О"))
        self.ledit_add_number.setPlaceholderText(_translate("MainWindow", "+7(XXX)-XXX-XX-XX"))
        self.label_4.setText(_translate("MainWindow", "Номер"))
        self.label_5.setText(_translate("MainWindow", "Пароль"))
        self.ledit_pass.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.btn_save_new_empl.setText(_translate("MainWindow", "Сохранить"))
        self.lbl_login.setText(_translate("MainWindow", "Логин"))
        self.ledit_login.setPlaceholderText(_translate("MainWindow", "Введите логин"))
