# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 412)
        MainWindow.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ledit_login_e_enter = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_login_e_enter.setGeometry(QtCore.QRect(220, 60, 261, 41))
        self.ledit_login_e_enter.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius: 5px;")
        self.ledit_login_e_enter.setObjectName("ledit_login_e_enter")
        self.ledit_pass_e_enter = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_pass_e_enter.setGeometry(QtCore.QRect(220, 120, 261, 41))
        self.ledit_pass_e_enter.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius: 5px;")
        self.ledit_pass_e_enter.setObjectName("ledit_pass_e_enter")
        self.btn_enter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enter.setGeometry(QtCore.QRect(260, 180, 171, 31))
        self.btn_enter.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(75, 75, 75);\n"
"font: 9pt \"Segoe UI\";\n"
"border-radius: 5px;")
        self.btn_enter.setObjectName("btn_enter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 220, 221, 51))
        self.label.setStyleSheet("color: rgb(0, 204, 204);")
        self.label.setObjectName("label")
        self.btn_reg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reg.setGeometry(QtCore.QRect(280, 290, 121, 31))
        self.btn_reg.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(75, 75, 75);\n"
"font: 9pt \"Segoe UI\";\n"
"border-radius: 5px;")
        self.btn_reg.setObjectName("btn_reg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ledit_login_e_enter.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.ledit_pass_e_enter.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.btn_enter.setText(_translate("MainWindow", "Войти"))
        self.label.setText(_translate("MainWindow", "Нет аккаунта? -Зарегистрируйся"))
        self.btn_reg.setText(_translate("MainWindow", "Регистрация"))
