# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debtors.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 527)
        Form.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 481, 41))
        self.label.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.tbl_wdgt_debtors = QtWidgets.QTableWidget(Form)
        self.tbl_wdgt_debtors.setGeometry(QtCore.QRect(0, 70, 501, 401))
        self.tbl_wdgt_debtors.setStyleSheet("background-color: rgb(143, 143, 143);\n"
"border-radius: 5px;")
        self.tbl_wdgt_debtors.setObjectName("tbl_wdgt_debtors")
        self.tbl_wdgt_debtors.setColumnCount(5)
        self.tbl_wdgt_debtors.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_wdgt_debtors.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_wdgt_debtors.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_wdgt_debtors.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_wdgt_debtors.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_wdgt_debtors.setHorizontalHeaderItem(4, item)
        self.btn_save_csv = QtWidgets.QPushButton(Form)
        self.btn_save_csv.setGeometry(QtCore.QRect(90, 490, 321, 21))
        self.btn_save_csv.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(75, 75, 75);\n"
"font: 9pt \"Segoe UI\";\n"
"border-radius: 5px;")
        self.btn_save_csv.setObjectName("btn_save_csv")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Список должников"))
        item = self.tbl_wdgt_debtors.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название книги"))
        item = self.tbl_wdgt_debtors.horizontalHeaderItem(1)
        item.setText(_translate("Form", "id книги"))
        item = self.tbl_wdgt_debtors.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Дедлайн"))
        item = self.tbl_wdgt_debtors.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Имя клиента"))
        item = self.tbl_wdgt_debtors.horizontalHeaderItem(4)
        item.setText(_translate("Form", "id клиента"))
        self.btn_save_csv.setText(_translate("Form", "Сохранить в CSV"))
