# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 600)
        MainWindow.setStyleSheet("background-color: rgb(85, 255, 255);\n"
                                 "background-color: rgb(0, 0, 86);\n"
                                 "color: rgb(0, 0, 75);\n"
                                 "background-color: rgb(75, 75, 75);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.centralwidget.setObjectName("centralwidget")
        self.btn_main_oper = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_oper.setGeometry(QtCore.QRect(60, 20, 161, 61))
        self.btn_main_oper.setStyleSheet("background-color: rgb(70, 212, 212);\n"
                                         "color: rgb(75, 75, 75);\n"
                                         "font: 14pt \"Segoe UI\";\n"
                                         "border-radius: 5px;")
        self.btn_main_oper.setIconSize(QtCore.QSize(80, 80))
        self.btn_main_oper.setObjectName("btn_main_oper")
        self.btn_main_books = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_books.setGeometry(QtCore.QRect(270, 20, 161, 61))
        self.btn_main_books.setStyleSheet("background-color: rgb(70, 212, 212);\n"
                                          "color: rgb(75, 75, 75);\n"
                                          "font: 14pt \"Segoe UI\";\n"
                                          "border-radius: 5px;")
        self.btn_main_books.setIconSize(QtCore.QSize(40, 40))
        self.btn_main_books.setObjectName("btn_main_books")
        self.btn_main_clients = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_clients.setGeometry(QtCore.QRect(490, 20, 161, 61))
        self.btn_main_clients.setStyleSheet("background-color: rgb(70, 212, 212);\n"
                                            "color: rgb(75, 75, 75);\n"
                                            "font: 14pt \"Segoe UI\";\n"
                                            "border-radius: 5px;")
        self.btn_main_clients.setIconSize(QtCore.QSize(40, 40))
        self.btn_main_clients.setObjectName("btn_main_clients")
        self.btn_main_empl = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_empl.setGeometry(QtCore.QRect(710, 20, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_main_empl.setFont(font)
        self.btn_main_empl.setStyleSheet("background-color: rgb(70, 212, 212);\n"
                                         "color: rgb(75, 75, 75);\n"
                                         "font: 14pt \"Segoe UI\";\n"
                                         "border-radius: 5px;")
        self.btn_main_empl.setIconSize(QtCore.QSize(38, 38))
        self.btn_main_empl.setObjectName("btn_main_empl")
        self.tbl_wdgt = QtWidgets.QTabWidget(self.centralwidget)
        self.tbl_wdgt.setEnabled(True)
        self.tbl_wdgt.setGeometry(QtCore.QRect(0, 90, 941, 461))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setKerning(True)
        self.tbl_wdgt.setFont(font)
        self.tbl_wdgt.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.tbl_wdgt.setObjectName("tbl_wdgt")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color: rgb(85, 0, 255);\n"
                               "background-color: rgb(75, 75, 75);\n"
                               "background-color: rgb(150, 50, 0);\n"
                               "background-color: rgb(150, 50, 0);\n"
                               "background-color: rgb(170, 0, 0);\n"
                               "background-color: rgb(170, 0, 0);\n"
                               "background-color: rgb(75, 75, 75);")
        self.tab.setObjectName("tab")
        self.btn_record_oper = QtWidgets.QPushButton(self.tab)
        self.btn_record_oper.setGeometry(QtCore.QRect(820, 10, 101, 31))
        self.btn_record_oper.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                           "color: rgb(75, 75, 75);\n"
                                           "font: 9pt \"Segoe UI\";\n"
                                           "border-radius: 5px;")
        self.btn_record_oper.setObjectName("btn_record_oper")
        self.ledit_id_book = QtWidgets.QLineEdit(self.tab)
        self.ledit_id_book.setGeometry(QtCore.QRect(30, 10, 141, 31))
        self.ledit_id_book.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                         "background-color: rgb(179, 179, 179);\n"
                                         "border-radius: 5px;")
        self.ledit_id_book.setObjectName("ledit_id_book")
        self.operation_cmb_box = QtWidgets.QComboBox(self.tab)
        self.operation_cmb_box.setGeometry(QtCore.QRect(480, 10, 91, 31))
        self.operation_cmb_box.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                             "border-radius: 5px;")
        self.operation_cmb_box.setObjectName("operation_cmb_box")
        self.operation_cmb_box.addItem("")
        self.operation_cmb_box.addItem("")
        self.days_cmb_box = QtWidgets.QComboBox(self.tab)
        self.days_cmb_box.setGeometry(QtCore.QRect(690, 10, 101, 31))
        self.days_cmb_box.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                        "border-radius: 5px;")
        self.days_cmb_box.setObjectName("days_cmb_box")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.days_cmb_box.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(420, 10, 61, 31))
        self.label_2.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(600, 10, 91, 31))
        self.label_3.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.ledit_name_client = QtWidgets.QLineEdit(self.tab)
        self.ledit_name_client.setGeometry(QtCore.QRect(220, 10, 141, 31))
        self.ledit_name_client.setStyleSheet("background-color: rgb(179, 179,179);\n"
                                             "border-radius: 5px;")
        self.ledit_name_client.setText("")
        self.ledit_name_client.setObjectName("ledit_name_client")
        self.btn_debtors = QtWidgets.QPushButton(self.tab)
        self.btn_debtors.setGeometry(QtCore.QRect(700, 190, 161, 41))
        self.btn_debtors.setStyleSheet("background-color: rgb(194, 37, 37);\n"
                                       "color: rgb(75, 75, 75);\n"
                                       "font: 13pt \"Segoe UI\";\n"
                                       "border-radius: 5px;")
        self.btn_debtors.setObjectName("btn_debtors")
        self.tbl_view_operations = QtWidgets.QTableView(self.tab)
        self.tbl_view_operations.setGeometry(QtCore.QRect(-10, 60, 601, 391))
        self.tbl_view_operations.setStyleSheet("background-color: rgb(143, 143, 143);\n"
                                               "border-radius: 5px;")
        self.tbl_view_operations.setObjectName("tbl_view_operations")
        self.tbl_wdgt.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.tab_2.setObjectName("tab_2")
        self.tbl_wdgt_all_books = QtWidgets.QTabWidget(self.tab_2)
        self.tbl_wdgt_all_books.setGeometry(QtCore.QRect(-10, 0, 1011, 491))
        self.tbl_wdgt_all_books.setObjectName("tbl_wdgt_all_books")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btn_add_book = QtWidgets.QPushButton(self.tab_5)
        self.btn_add_book.setGeometry(QtCore.QRect(770, 10, 141, 41))
        self.btn_add_book.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                        "color: rgb(75, 75, 75);\n"
                                        "font: 9pt \"Segoe UI\";\n"
                                        "border-radius: 5px;")
        self.btn_add_book.setObjectName("btn_add_book")
        self.tbl_view_books = QtWidgets.QTableView(self.tab_5)
        self.tbl_view_books.setGeometry(QtCore.QRect(0, 0, 681, 431))
        self.tbl_view_books.setStyleSheet("background-color: rgb(143, 143, 143);\n"
                                          "border-radius: 5px;")
        self.tbl_view_books.setObjectName("tbl_view_books")
        self.btn_reload_books = QtWidgets.QPushButton(self.tab_5)
        self.btn_reload_books.setGeometry(QtCore.QRect(700, 10, 41, 41))
        self.btn_reload_books.setStyleSheet("background-color: rgb(70, 212, 212);\n"
                                            "color: rgb(75, 75, 75);\n"
                                            "font: 14pt \"Segoe UI\";\n"
                                            "border-radius: 5px;")
        self.btn_reload_books.setObjectName("btn_reload_books")
        self.tbl_wdgt_all_books.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.cmb_value_search = QtWidgets.QComboBox(self.tab_9)
        self.cmb_value_search.setGeometry(QtCore.QRect(40, 10, 121, 31))
        self.cmb_value_search.setStyleSheet("background-color: rgb(179, 179,179);\n"
                                            "border-radius: 5px;")
        self.cmb_value_search.setObjectName("cmb_value_search")
        self.cmb_value_search.addItem("")
        self.cmb_value_search.addItem("")
        self.ledit_value_search = QtWidgets.QLineEdit(self.tab_9)
        self.ledit_value_search.setGeometry(QtCore.QRect(40, 60, 141, 31))
        self.ledit_value_search.setStyleSheet("background-color: rgb(179, 179,179);\n"
                                              "border-radius: 5px;")
        self.ledit_value_search.setObjectName("ledit_value_search")
        self.btn_search_book = QtWidgets.QPushButton(self.tab_9)
        self.btn_search_book.setGeometry(QtCore.QRect(270, 30, 131, 41))
        self.btn_search_book.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                           "color: rgb(75, 75, 75);\n"
                                           "font: 12pt \"Segoe UI\";\n"
                                           "border-radius: 5px;")
        self.btn_search_book.setObjectName("btn_search_book")
        self.lst_wdgt_btn_books = QtWidgets.QListWidget(self.tab_9)
        self.lst_wdgt_btn_books.setGeometry(QtCore.QRect(40, 120, 361, 251))
        self.lst_wdgt_btn_books.setStyleSheet("background-color: rgb(179, 179,179);\n"
                                              "background-color: rgb(68, 68, 68);\n"
                                              "border-radius: 5px;")
        self.lst_wdgt_btn_books.setObjectName("lst_wdgt_btn_books")
        self.tbl_wdgt_all_books.addTab(self.tab_9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.ledit_search_id_upd = QtWidgets.QLineEdit(self.tab_6)
        self.ledit_search_id_upd.setGeometry(QtCore.QRect(40, 40, 151, 31))
        self.ledit_search_id_upd.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                               "background-color: rgb(179, 179, 179);\n"
                                               "border-radius: 5px;")
        self.ledit_search_id_upd.setObjectName("ledit_search_id_upd")
        self.ledit_update_title = QtWidgets.QLineEdit(self.tab_6)
        self.ledit_update_title.setGeometry(QtCore.QRect(140, 170, 181, 31))
        self.ledit_update_title.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                              "background-color: rgb(179, 179, 179);\n"
                                              "border-radius: 5px;")
        self.ledit_update_title.setObjectName("ledit_update_title")
        self.lbl_search_title = QtWidgets.QLabel(self.tab_6)
        self.lbl_search_title.setGeometry(QtCore.QRect(40, 10, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lbl_search_title.setFont(font)
        self.lbl_search_title.setObjectName("lbl_search_title")
        self.btn_search_book_update = QtWidgets.QPushButton(self.tab_6)
        self.btn_search_book_update.setGeometry(QtCore.QRect(230, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search_book_update.setFont(font)
        self.btn_search_book_update.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                                  "color: rgb(75, 75, 75);\n"
                                                  "font: 9pt \"Segoe UI\";\n"
                                                  "border-radius: 5px;")
        self.btn_search_book_update.setObjectName("btn_search_book_update")
        self.ledit_update_year = QtWidgets.QLineEdit(self.tab_6)
        self.ledit_update_year.setGeometry(QtCore.QRect(140, 220, 181, 31))
        self.ledit_update_year.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                             "background-color: rgb(179, 179, 179);\n"
                                             "border-radius: 5px;")
        self.ledit_update_year.setText("")
        self.ledit_update_year.setObjectName("ledit_update_year")
        self.ledit_update_genre = QtWidgets.QLineEdit(self.tab_6)
        self.ledit_update_genre.setGeometry(QtCore.QRect(140, 270, 181, 31))
        self.ledit_update_genre.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                              "background-color: rgb(179, 179, 179);\n"
                                              "border-radius: 5px;")
        self.ledit_update_genre.setText("")
        self.ledit_update_genre.setObjectName("ledit_update_genre")
        self.ledit_update_author = QtWidgets.QLineEdit(self.tab_6)
        self.ledit_update_author.setGeometry(QtCore.QRect(140, 320, 181, 31))
        self.ledit_update_author.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                               "background-color: rgb(179, 179, 179);\n"
                                               "border-radius: 5px;")
        self.ledit_update_author.setObjectName("ledit_update_author")
        self.txt_edit_update_desc = QtWidgets.QTextEdit(self.tab_6)
        self.txt_edit_update_desc.setGeometry(QtCore.QRect(470, 160, 411, 221))
        self.txt_edit_update_desc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                "border-radius: 5px;")
        self.txt_edit_update_desc.setObjectName("txt_edit_update_desc")
        self.lbl_update_title = QtWidgets.QLabel(self.tab_6)
        self.lbl_update_title.setGeometry(QtCore.QRect(50, 170, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lbl_update_title.setFont(font)
        self.lbl_update_title.setObjectName("lbl_update_title")
        self.lbl_update_year = QtWidgets.QLabel(self.tab_6)
        self.lbl_update_year.setGeometry(QtCore.QRect(50, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lbl_update_year.setFont(font)
        self.lbl_update_year.setObjectName("lbl_update_year")
        self.lbl_update_genre = QtWidgets.QLabel(self.tab_6)
        self.lbl_update_genre.setGeometry(QtCore.QRect(50, 270, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lbl_update_genre.setFont(font)
        self.lbl_update_genre.setObjectName("lbl_update_genre")
        self.lbl_update_author = QtWidgets.QLabel(self.tab_6)
        self.lbl_update_author.setGeometry(QtCore.QRect(50, 320, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lbl_update_author.setFont(font)
        self.lbl_update_author.setObjectName("lbl_update_author")
        self.btn_upd_val_book = QtWidgets.QPushButton(self.tab_6)
        self.btn_upd_val_book.setGeometry(QtCore.QRect(60, 370, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_upd_val_book.setFont(font)
        self.btn_upd_val_book.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                            "color: rgb(75, 75, 75);\n"
                                            "font: 9pt \"Segoe UI\";\n"
                                            "border-radius: 5px;")
        self.btn_upd_val_book.setObjectName("btn_upd_val_book")
        self.btn_del_book = QtWidgets.QPushButton(self.tab_6)
        self.btn_del_book.setGeometry(QtCore.QRect(190, 370, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_del_book.setFont(font)
        self.btn_del_book.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                        "color: rgb(75, 75, 75);\n"
                                        "font: 10pt \"Segoe UI\";\n"
                                        "border-radius: 5px;")
        self.btn_del_book.setObjectName("btn_del_book")
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setGeometry(QtCore.QRect(350, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tbl_wdgt_all_books.addTab(self.tab_6, "")
        self.tbl_wdgt.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.tab_3.setObjectName("tab_3")
        self.tbl_wdgt_all_clients = QtWidgets.QTabWidget(self.tab_3)
        self.tbl_wdgt_all_clients.setEnabled(True)
        self.tbl_wdgt_all_clients.setGeometry(QtCore.QRect(-10, 0, 1001, 491))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tbl_wdgt_all_clients.setFont(font)
        self.tbl_wdgt_all_clients.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.tbl_wdgt_all_clients.setObjectName("tbl_wdgt_all_clients")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.btn_add_client = QtWidgets.QPushButton(self.tab_7)
        self.btn_add_client.setGeometry(QtCore.QRect(660, 330, 151, 41))
        self.btn_add_client.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                          "color: rgb(75, 75, 75);\n"
                                          "font: 9pt \"Segoe UI\";\n"
                                          "border-radius: 5px;")
        self.btn_add_client.setObjectName("btn_add_client")
        self.tbl_view_clients = QtWidgets.QTableView(self.tab_7)
        self.tbl_view_clients.setGeometry(QtCore.QRect(20, 30, 521, 361))
        self.tbl_view_clients.setStyleSheet("background-color: rgb(143, 143, 143);\n"
                                            "border-radius: 5px;")
        self.tbl_view_clients.setObjectName("tbl_view_clients")
        self.lbl_get_id = QtWidgets.QLabel(self.tab_7)
        self.lbl_get_id.setGeometry(QtCore.QRect(590, 50, 301, 21))
        self.lbl_get_id.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lbl_get_id.setObjectName("lbl_get_id")
        self.ledit_num_get_id = QtWidgets.QLineEdit(self.tab_7)
        self.ledit_num_get_id.setGeometry(QtCore.QRect(590, 80, 171, 31))
        self.ledit_num_get_id.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                            "background-color: rgb(179, 179, 179);\n"
                                            "border-radius: 5px;")
        self.ledit_num_get_id.setObjectName("ledit_num_get_id")
        self.btn_search_get_id = QtWidgets.QPushButton(self.tab_7)
        self.btn_search_get_id.setGeometry(QtCore.QRect(780, 80, 81, 31))
        self.btn_search_get_id.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                             "color: rgb(75, 75, 75);\n"
                                             "font: 9pt \"Segoe UI\";\n"
                                             "border-radius: 5px;")
        self.btn_search_get_id.setObjectName("btn_search_get_id")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(600, 140, 31, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.ledit_out_id = QtWidgets.QLineEdit(self.tab_7)
        self.ledit_out_id.setEnabled(False)
        self.ledit_out_id.setGeometry(QtCore.QRect(640, 140, 91, 20))
        self.ledit_out_id.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                        "background-color: rgb(179, 179, 179);\n"
                                        "border-radius: 5px;")
        self.ledit_out_id.setObjectName("ledit_out_id")
        self.btn_reload_clients_tab = QtWidgets.QPushButton(self.tab_7)
        self.btn_reload_clients_tab.setGeometry(QtCore.QRect(580, 330, 41, 41))
        self.btn_reload_clients_tab.setStyleSheet("background-color: rgb(70, 212, 212);\n"
                                                  "color: rgb(75, 75, 75);\n"
                                                  "font: 14pt \"Segoe UI\";\n"
                                                  "border-radius: 5px;")
        self.btn_reload_clients_tab.setObjectName("btn_reload_clients_tab")
        self.tbl_wdgt_all_clients.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.ledit_search_client_id = QtWidgets.QLineEdit(self.tab_8)
        self.ledit_search_client_id.setGeometry(QtCore.QRect(40, 40, 151, 31))
        self.ledit_search_client_id.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                                  "background-color: rgb(179, 179, 179);\n"
                                                  "border-radius: 5px;")
        self.ledit_search_client_id.setObjectName("ledit_search_client_id")
        self.ledit_update_name_c = QtWidgets.QLineEdit(self.tab_8)
        self.ledit_update_name_c.setGeometry(QtCore.QRect(140, 140, 181, 31))
        self.ledit_update_name_c.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                               "background-color: rgb(179, 179, 179);\n"
                                               "border-radius: 5px;")
        self.ledit_update_name_c.setPlaceholderText("")
        self.ledit_update_name_c.setObjectName("ledit_update_name_c")
        self.lbl_search_client_2 = QtWidgets.QLabel(self.tab_8)
        self.lbl_search_client_2.setGeometry(QtCore.QRect(40, 10, 391, 21))
        self.lbl_search_client_2.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.lbl_search_client_2.setObjectName("lbl_search_client_2")
        self.btn_search_client_num = QtWidgets.QPushButton(self.tab_8)
        self.btn_search_client_num.setGeometry(QtCore.QRect(270, 40, 81, 31))
        self.btn_search_client_num.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                                 "color: rgb(75, 75, 75);\n"
                                                 "font: 9pt \"Segoe UI\";\n"
                                                 "border-radius: 5px;")
        self.btn_search_client_num.setObjectName("btn_search_client_num")
        self.lnl_inf_2 = QtWidgets.QLabel(self.tab_8)
        self.lnl_inf_2.setGeometry(QtCore.QRect(40, 100, 721, 31))
        self.lnl_inf_2.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.lnl_inf_2.setObjectName("lnl_inf_2")
        self.ledit_update_num_c = QtWidgets.QLineEdit(self.tab_8)
        self.ledit_update_num_c.setGeometry(QtCore.QRect(140, 190, 181, 31))
        self.ledit_update_num_c.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                              "background-color: rgb(179, 179, 179);\n"
                                              "border-radius: 5px;")
        self.ledit_update_num_c.setPlaceholderText("")
        self.ledit_update_num_c.setObjectName("ledit_update_num_c")
        self.ledit_update_mail_c = QtWidgets.QLineEdit(self.tab_8)
        self.ledit_update_mail_c.setGeometry(QtCore.QRect(140, 240, 181, 31))
        self.ledit_update_mail_c.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                               "background-color: rgb(179, 179, 179);\n"
                                               "border-radius: 5px;")
        self.ledit_update_mail_c.setPlaceholderText("")
        self.ledit_update_mail_c.setObjectName("ledit_update_mail_c")
        self.lbl_update_name_c = QtWidgets.QLabel(self.tab_8)
        self.lbl_update_name_c.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.lbl_update_name_c.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_name_c.setObjectName("lbl_update_name_c")
        self.lbl_update_num_c = QtWidgets.QLabel(self.tab_8)
        self.lbl_update_num_c.setGeometry(QtCore.QRect(50, 190, 71, 21))
        self.lbl_update_num_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
                                            "font: 8pt \"Segoe UI\";")
        self.lbl_update_num_c.setObjectName("lbl_update_num_c")
        self.lbl_update_mail_c = QtWidgets.QLabel(self.tab_8)
        self.lbl_update_mail_c.setGeometry(QtCore.QRect(50, 230, 71, 21))
        self.lbl_update_mail_c.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_mail_c.setObjectName("lbl_update_mail_c")
        self.btn_update_client = QtWidgets.QPushButton(self.tab_8)
        self.btn_update_client.setGeometry(QtCore.QRect(50, 300, 111, 23))
        self.btn_update_client.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                             "color: rgb(75, 75, 75);\n"
                                             "font: 10pt \"Segoe UI\";\n"
                                             "border-radius: 5px;")
        self.btn_update_client.setObjectName("btn_update_client")
        self.btn_del_client = QtWidgets.QPushButton(self.tab_8)
        self.btn_del_client.setGeometry(QtCore.QRect(220, 300, 121, 23))
        self.btn_del_client.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                          "color: rgb(75, 75, 75);\n"
                                          "font: 10pt \"Segoe UI\";\n"
                                          "border-radius: 5px;")
        self.btn_del_client.setObjectName("btn_del_client")
        self.lbl_update_adres = QtWidgets.QLabel(self.tab_8)
        self.lbl_update_adres.setGeometry(QtCore.QRect(370, 140, 71, 21))
        self.lbl_update_adres.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_adres.setObjectName("lbl_update_adres")
        self.ledit_update_adres = QtWidgets.QLineEdit(self.tab_8)
        self.ledit_update_adres.setGeometry(QtCore.QRect(460, 140, 181, 31))
        self.ledit_update_adres.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                              "background-color: rgb(179, 179, 179);\n"
                                              "border-radius: 5px;")
        self.ledit_update_adres.setPlaceholderText("")
        self.ledit_update_adres.setObjectName("ledit_update_adres")
        self.lbl_update_bdate = QtWidgets.QLabel(self.tab_8)
        self.lbl_update_bdate.setGeometry(QtCore.QRect(330, 180, 111, 21))
        self.lbl_update_bdate.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_bdate.setObjectName("lbl_update_bdate")
        self.clndr_wdgt_add_date = QtWidgets.QCalendarWidget(self.tab_8)
        self.clndr_wdgt_add_date.setGeometry(QtCore.QRect(460, 180, 331, 221))
        self.clndr_wdgt_add_date.setStyleSheet("font-size:12px;\n"
                                               "color:rgb(180,180,180);\n"
                                               "background-color:rgb(75, 75, 75);\n"
                                               "selection-background-color:rgb(64,64,64);\n"
                                               "selection-color:rgb(0,255,0);\n"
                                               " ")
        self.clndr_wdgt_add_date.setObjectName("clndr_wdgt_add_date")
        self.tbl_wdgt_all_clients.addTab(self.tab_8, "")
        self.tbl_wdgt.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.tab_4.setObjectName("tab_4")
        self.tb_wdgt_empl = QtWidgets.QTabWidget(self.tab_4)
        self.tb_wdgt_empl.setGeometry(QtCore.QRect(0, 0, 951, 481))
        self.tb_wdgt_empl.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.tb_wdgt_empl.setObjectName("tb_wdgt_empl")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.ledit_add_name_e = QtWidgets.QLineEdit(self.tab_11)
        self.ledit_add_name_e.setGeometry(QtCore.QRect(130, 10, 131, 31))
        self.ledit_add_name_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                            "background-color: rgb(179, 179, 179);\n"
                                            "border-radius: 5px;")
        self.ledit_add_name_e.setObjectName("ledit_add_name_e")
        self.ledit_add_num_e = QtWidgets.QLineEdit(self.tab_11)
        self.ledit_add_num_e.setGeometry(QtCore.QRect(130, 60, 131, 31))
        self.ledit_add_num_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                           "background-color: rgb(179, 179, 179);\n"
                                           "border-radius: 5px;")
        self.ledit_add_num_e.setObjectName("ledit_add_num_e")
        self.ledit_add_pass_e = QtWidgets.QLineEdit(self.tab_11)
        self.ledit_add_pass_e.setGeometry(QtCore.QRect(130, 160, 131, 31))
        self.ledit_add_pass_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                            "background-color: rgb(179, 179, 179);\n"
                                            "border-radius: 5px;")
        self.ledit_add_pass_e.setObjectName("ledit_add_pass_e")
        self.lbl_add_name_e = QtWidgets.QLabel(self.tab_11)
        self.lbl_add_name_e.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.lbl_add_name_e.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_name_e.setObjectName("lbl_add_name_e")
        self.lbl_add_num_e = QtWidgets.QLabel(self.tab_11)
        self.lbl_add_num_e.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.lbl_add_num_e.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_num_e.setObjectName("lbl_add_num_e")
        self.lbl_add_pass_e = QtWidgets.QLabel(self.tab_11)
        self.lbl_add_pass_e.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.lbl_add_pass_e.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_pass_e.setObjectName("lbl_add_pass_e")
        self.btn_add_e = QtWidgets.QPushButton(self.tab_11)
        self.btn_add_e.setGeometry(QtCore.QRect(70, 240, 111, 31))
        self.btn_add_e.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                     "color: rgb(75, 75, 75);\n"
                                     "font: 9pt \"Segoe UI\";\n"
                                     "border-radius: 5px;")
        self.btn_add_e.setObjectName("btn_add_e")
        self.ledit_login_e = QtWidgets.QLineEdit(self.tab_11)
        self.ledit_login_e.setGeometry(QtCore.QRect(130, 110, 131, 31))
        self.ledit_login_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                         "background-color: rgb(179, 179, 179);\n"
                                         "border-radius: 5px;")
        self.ledit_login_e.setObjectName("ledit_login_e")
        self.lbl_add_num_e_2 = QtWidgets.QLabel(self.tab_11)
        self.lbl_add_num_e_2.setGeometry(QtCore.QRect(30, 120, 71, 21))
        self.lbl_add_num_e_2.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_add_num_e_2.setObjectName("lbl_add_num_e_2")
        self.tb_wdgt_empl.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.lbl_update_name_e = QtWidgets.QLabel(self.tab_12)
        self.lbl_update_name_e.setGeometry(QtCore.QRect(20, 190, 81, 21))
        self.lbl_update_name_e.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_name_e.setObjectName("lbl_update_name_e")
        self.lbl_update_num_e = QtWidgets.QLabel(self.tab_12)
        self.lbl_update_num_e.setGeometry(QtCore.QRect(20, 240, 81, 21))
        self.lbl_update_num_e.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_num_e.setObjectName("lbl_update_num_e")
        self.lbl_update_pass_e_2 = QtWidgets.QLabel(self.tab_12)
        self.lbl_update_pass_e_2.setGeometry(QtCore.QRect(20, 290, 81, 21))
        self.lbl_update_pass_e_2.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_pass_e_2.setObjectName("lbl_update_pass_e_2")
        self.ledit_update_name_e = QtWidgets.QLineEdit(self.tab_12)
        self.ledit_update_name_e.setGeometry(QtCore.QRect(120, 180, 131, 31))
        self.ledit_update_name_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                               "background-color: rgb(179, 179, 179);\n"
                                               "border-radius: 5px;")
        self.ledit_update_name_e.setObjectName("ledit_update_name_e")
        self.ledit_update_num_e = QtWidgets.QLineEdit(self.tab_12)
        self.ledit_update_num_e.setGeometry(QtCore.QRect(120, 230, 131, 31))
        self.ledit_update_num_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                              "background-color: rgb(179, 179, 179);\n"
                                              "border-radius: 5px;")
        self.ledit_update_num_e.setObjectName("ledit_update_num_e")
        self.ledit_update_pass_e = QtWidgets.QLineEdit(self.tab_12)
        self.ledit_update_pass_e.setGeometry(QtCore.QRect(120, 280, 131, 31))
        self.ledit_update_pass_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                               "background-color: rgb(179, 179, 179);\n"
                                               "border-radius: 5px;")
        self.ledit_update_pass_e.setObjectName("ledit_update_pass_e")
        self.btn_update_e = QtWidgets.QPushButton(self.tab_12)
        self.btn_update_e.setGeometry(QtCore.QRect(80, 340, 121, 31))
        self.btn_update_e.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                        "color: rgb(75, 75, 75);\n"
                                        "font: 9pt \"Segoe UI\";\n"
                                        "border-radius: 5px;")
        self.btn_update_e.setObjectName("btn_update_e")
        self.lbl_search_login = QtWidgets.QLabel(self.tab_12)
        self.lbl_search_login.setGeometry(QtCore.QRect(20, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lbl_search_login.setFont(font)
        self.lbl_search_login.setObjectName("lbl_search_login")
        self.ledit_search_empl_login = QtWidgets.QLineEdit(self.tab_12)
        self.ledit_search_empl_login.setGeometry(QtCore.QRect(20, 50, 151, 31))
        self.ledit_search_empl_login.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                                   "background-color: rgb(179, 179, 179);\n"
                                                   "border-radius: 5px;")
        self.ledit_search_empl_login.setObjectName("ledit_search_empl_login")
        self.btn_search_empl_login = QtWidgets.QPushButton(self.tab_12)
        self.btn_search_empl_login.setGeometry(QtCore.QRect(210, 50, 81, 31))
        self.btn_search_empl_login.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                                 "color: rgb(75, 75, 75);\n"
                                                 "font: 9pt \"Segoe UI\";\n"
                                                 "border-radius: 5px;")
        self.btn_search_empl_login.setObjectName("btn_search_empl_login")
        self.lbl_update_login_e = QtWidgets.QLabel(self.tab_12)
        self.lbl_update_login_e.setGeometry(QtCore.QRect(20, 140, 91, 21))
        self.lbl_update_login_e.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.lbl_update_login_e.setObjectName("lbl_update_login_e")
        self.ledit_update_login_e = QtWidgets.QLineEdit(self.tab_12)
        self.ledit_update_login_e.setGeometry(QtCore.QRect(120, 130, 131, 31))
        self.ledit_update_login_e.setStyleSheet("alternate-background-color: rgb(85, 170, 255);\n"
                                                "background-color: rgb(179, 179, 179);\n"
                                                "border-radius: 5px;")
        self.ledit_update_login_e.setObjectName("ledit_update_login_e")
        self.tb_wdgt_empl.addTab(self.tab_12, "")
        self.tbl_wdgt.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tbl_wdgt.setCurrentIndex(0)
        self.tbl_wdgt_all_books.setCurrentIndex(1)
        self.tbl_wdgt_all_clients.setCurrentIndex(0)
        self.tb_wdgt_empl.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_main_oper.setText(_translate("MainWindow", "📄 Операция"))
        self.btn_main_books.setText(_translate("MainWindow", " 📚  Книги"))
        self.btn_main_clients.setText(_translate("MainWindow", "🧑‍🎓 Читатели"))
        self.btn_main_empl.setText(_translate("MainWindow", "🧑‍💻 Сотрудники"))
        self.btn_record_oper.setText(_translate("MainWindow", "Добавить ✔️"))
        self.ledit_id_book.setPlaceholderText(_translate("MainWindow", "Введите id книги"))
        self.operation_cmb_box.setItemText(0, _translate("MainWindow", "Выдача"))
        self.operation_cmb_box.setItemText(1, _translate("MainWindow", "Возврат"))
        self.days_cmb_box.setItemText(0, _translate("MainWindow", "1"))
        self.days_cmb_box.setItemText(1, _translate("MainWindow", "2"))
        self.days_cmb_box.setItemText(2, _translate("MainWindow", "3"))
        self.days_cmb_box.setItemText(3, _translate("MainWindow", "4"))
        self.days_cmb_box.setItemText(4, _translate("MainWindow", "5"))
        self.days_cmb_box.setItemText(5, _translate("MainWindow", "6"))
        self.days_cmb_box.setItemText(6, _translate("MainWindow", "7"))
        self.days_cmb_box.setItemText(7, _translate("MainWindow", "8"))
        self.days_cmb_box.setItemText(8, _translate("MainWindow", "9"))
        self.days_cmb_box.setItemText(9, _translate("MainWindow", "10"))
        self.days_cmb_box.setItemText(10, _translate("MainWindow", "11"))
        self.days_cmb_box.setItemText(11, _translate("MainWindow", "12"))
        self.days_cmb_box.setItemText(12, _translate("MainWindow", "13"))
        self.days_cmb_box.setItemText(13, _translate("MainWindow", "14"))
        self.label_2.setText(_translate("MainWindow", "Тип"))
        self.label_3.setText(_translate("MainWindow", "Кол-во дней"))
        self.ledit_name_client.setPlaceholderText(_translate("MainWindow", "Введите id клиента"))
        self.btn_debtors.setText(_translate("MainWindow", "Должники"))
        self.tbl_wdgt.setTabText(self.tbl_wdgt.indexOf(self.tab), _translate("MainWindow", "операция"))
        self.btn_add_book.setText(_translate("MainWindow", "Добавить книгу ✔️"))
        self.btn_reload_books.setText(_translate("MainWindow", "🔃"))
        self.tbl_wdgt_all_books.setTabText(self.tbl_wdgt_all_books.indexOf(self.tab_5),
                                           _translate("MainWindow", "Книги"))
        self.cmb_value_search.setItemText(0, _translate("MainWindow", "Автор"))
        self.cmb_value_search.setItemText(1, _translate("MainWindow", "Название"))
        self.ledit_value_search.setPlaceholderText(_translate("MainWindow", "Введите"))
        self.btn_search_book.setText(_translate("MainWindow", "🔍 Поиск"))
        self.tbl_wdgt_all_books.setTabText(self.tbl_wdgt_all_books.indexOf(self.tab_9),
                                           _translate("MainWindow", "Поиск"))
        self.ledit_search_id_upd.setPlaceholderText(_translate("MainWindow", "Введите название"))
        self.ledit_update_title.setPlaceholderText(_translate("MainWindow", "Введите название"))
        self.lbl_search_title.setText(_translate("MainWindow", "Поиск книги по id"))
        self.btn_search_book_update.setText(_translate("MainWindow", "🔍 Поиск"))
        self.ledit_update_year.setPlaceholderText(_translate("MainWindow", "Введите год"))
        self.ledit_update_genre.setPlaceholderText(_translate("MainWindow", "Введите жанр"))
        self.ledit_update_author.setPlaceholderText(_translate("MainWindow", "Введите автора"))
        self.lbl_update_title.setText(_translate("MainWindow", "Название"))
        self.lbl_update_year.setText(_translate("MainWindow", "Год"))
        self.lbl_update_genre.setText(_translate("MainWindow", "Жанр"))
        self.lbl_update_author.setText(_translate("MainWindow", "Автор"))
        self.btn_upd_val_book.setText(_translate("MainWindow", "Обновить 🔄"))
        self.btn_del_book.setText(_translate("MainWindow", "🗑️ Удалить"))
        self.label.setText(_translate("MainWindow", "Описание"))
        self.tbl_wdgt_all_books.setTabText(self.tbl_wdgt_all_books.indexOf(self.tab_6),
                                           _translate("MainWindow", "Редакт или удаление"))
        self.tbl_wdgt.setTabText(self.tbl_wdgt.indexOf(self.tab_2), _translate("MainWindow", "книга"))
        self.btn_add_client.setText(_translate("MainWindow", "Добавить читателя ✔️"))
        self.lbl_get_id.setText(_translate("MainWindow", "Для поиска id клиента в бд"))
        self.ledit_num_get_id.setPlaceholderText(_translate("MainWindow", "Введите номер телефона"))
        self.btn_search_get_id.setText(_translate("MainWindow", "🔍 Поиск"))
        self.label_4.setText(_translate("MainWindow", "ID:"))
        self.btn_reload_clients_tab.setText(_translate("MainWindow", "🔃"))
        self.tbl_wdgt_all_clients.setTabText(self.tbl_wdgt_all_clients.indexOf(self.tab_7),
                                             _translate("MainWindow", "Читатели"))
        self.ledit_search_client_id.setPlaceholderText(_translate("MainWindow", "Введите id"))
        self.lbl_search_client_2.setText(_translate("MainWindow", "Поиск читателя по id"))
        self.btn_search_client_num.setText(_translate("MainWindow", "🔍 Поиск"))
        self.lnl_inf_2.setText(
            _translate("MainWindow", "Если вы ввели корректный номер, поля ниже должны были заполнится"))
        self.lbl_update_name_c.setText(_translate("MainWindow", "имя"))
        self.lbl_update_num_c.setText(_translate("MainWindow", "номер"))
        self.lbl_update_mail_c.setText(_translate("MainWindow", "почта"))
        self.btn_update_client.setText(_translate("MainWindow", "Обновить 🔄"))
        self.btn_del_client.setText(_translate("MainWindow", "🗑️ Удалить"))
        self.lbl_update_adres.setText(_translate("MainWindow", "Адрес"))
        self.lbl_update_bdate.setText(_translate("MainWindow", "Дата рождения"))
        self.tbl_wdgt_all_clients.setTabText(self.tbl_wdgt_all_clients.indexOf(self.tab_8),
                                             _translate("MainWindow", "Редакт или удаление"))
        self.tbl_wdgt.setTabText(self.tbl_wdgt.indexOf(self.tab_3), _translate("MainWindow", "читатель"))
        self.ledit_add_name_e.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.ledit_add_num_e.setPlaceholderText(_translate("MainWindow", "Введите номер"))
        self.ledit_add_pass_e.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.lbl_add_name_e.setText(_translate("MainWindow", "Имя"))
        self.lbl_add_num_e.setText(_translate("MainWindow", "Номер"))
        self.lbl_add_pass_e.setText(_translate("MainWindow", "Пароль"))
        self.btn_add_e.setText(_translate("MainWindow", "Добавить ✔️"))
        self.ledit_login_e.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.lbl_add_num_e_2.setText(_translate("MainWindow", "Логин"))
        self.tb_wdgt_empl.setTabText(self.tb_wdgt_empl.indexOf(self.tab_11),
                                     _translate("MainWindow", "Добавить сотруднка"))
        self.lbl_update_name_e.setText(_translate("MainWindow", "Имя"))
        self.lbl_update_num_e.setText(_translate("MainWindow", "Номер"))
        self.lbl_update_pass_e_2.setText(_translate("MainWindow", "Пароль"))
        self.ledit_update_name_e.setPlaceholderText(_translate("MainWindow", "Измените имя"))
        self.ledit_update_num_e.setPlaceholderText(_translate("MainWindow", "Измените номер"))
        self.ledit_update_pass_e.setPlaceholderText(_translate("MainWindow", "Измените пароль"))
        self.btn_update_e.setText(_translate("MainWindow", "Изменить 🔄"))
        self.lbl_search_login.setText(_translate("MainWindow", "Поиск сотрудника по логину"))
        self.ledit_search_empl_login.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.btn_search_empl_login.setText(_translate("MainWindow", "🔍 Поиск"))
        self.lbl_update_login_e.setText(_translate("MainWindow", "Логин"))
        self.ledit_update_login_e.setPlaceholderText(_translate("MainWindow", "Измените логин"))
        self.tb_wdgt_empl.setTabText(self.tb_wdgt_empl.indexOf(self.tab_12), _translate("MainWindow", "Редактировать "))
        self.tbl_wdgt.setTabText(self.tbl_wdgt.indexOf(self.tab_4), _translate("MainWindow", "сотрудник"))
