# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_information_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(556, 767)
        widget.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.label_pixmap = QtWidgets.QLabel(widget)
        self.label_pixmap.setGeometry(QtCore.QRect(10, 10, 321, 431))
        self.label_pixmap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_pixmap.setText("")
        self.label_pixmap.setObjectName("label_pixmap")
        self.label_name_book1 = QtWidgets.QLabel(widget)
        self.label_name_book1.setGeometry(QtCore.QRect(380, 10, 161, 31))
        self.label_name_book1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "font: 87 16pt \"Segoe UI Black\";")
        self.label_name_book1.setObjectName("label_name_book1")
        self.label_name_book = QtWidgets.QLabel(widget)
        self.label_name_book.setGeometry(QtCore.QRect(350, 50, 201, 31))
        self.label_name_book.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "font: 10pt \"Segoe UI\";")
        self.label_name_book.setText("")
        self.label_name_book.setObjectName("label_name_book")
        self.label_name_author1 = QtWidgets.QLabel(widget)
        self.label_name_author1.setGeometry(QtCore.QRect(390, 100, 161, 31))
        self.label_name_author1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "font: 87 16pt \"Segoe UI Black\";")
        self.label_name_author1.setObjectName("label_name_author1")
        self.label_name_author = QtWidgets.QLabel(widget)
        self.label_name_author.setGeometry(QtCore.QRect(350, 140, 201, 31))
        self.label_name_author.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "font: 10pt \"Segoe UI\";")
        self.label_name_author.setText("")
        self.label_name_author.setObjectName("label_name_author")
        self.label_name_genre1 = QtWidgets.QLabel(widget)
        self.label_name_genre1.setGeometry(QtCore.QRect(400, 190, 161, 31))
        self.label_name_genre1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "font: 87 16pt \"Segoe UI Black\";")
        self.label_name_genre1.setObjectName("label_name_genre1")
        self.label_name_genre = QtWidgets.QLabel(widget)
        self.label_name_genre.setGeometry(QtCore.QRect(350, 230, 201, 31))
        self.label_name_genre.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "font: 10pt \"Segoe UI\";")
        self.label_name_genre.setText("")
        self.label_name_genre.setObjectName("label_name_genre")
        self.label_id1 = QtWidgets.QLabel(widget)
        self.label_id1.setGeometry(QtCore.QRect(420, 370, 41, 31))
        self.label_id1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "font: 87 16pt \"Segoe UI Black\";")
        self.label_id1.setObjectName("label_id1")
        self.label_id = QtWidgets.QLabel(widget)
        self.label_id.setGeometry(QtCore.QRect(360, 410, 151, 21))
        self.label_id.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "font: 11pt \"Segoe UI\";")
        self.label_id.setText("")
        self.label_id.setObjectName("label_id")
        self.label_description1 = QtWidgets.QLabel(widget)
        self.label_description1.setGeometry(QtCore.QRect(210, 500, 141, 21))
        self.label_description1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "font: 87 16pt \"Segoe UI Black\";")
        self.label_description1.setObjectName("label_description1")
        self.label_year1 = QtWidgets.QLabel(widget)
        self.label_year1.setGeometry(QtCore.QRect(360, 280, 191, 31))
        self.label_year1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "font: 87 16pt \"Segoe UI Black\";")
        self.label_year1.setObjectName("label_year1")
        self.label_year = QtWidgets.QLabel(widget)
        self.label_year.setGeometry(QtCore.QRect(350, 320, 201, 31))
        self.label_year.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 10pt \"Segoe UI\";")
        self.label_year.setText("")
        self.label_year.setObjectName("label_year")
        self.txt_edit_description = QtWidgets.QTextEdit(widget)
        self.txt_edit_description.setGeometry(QtCore.QRect(10, 530, 551, 241))
        self.txt_edit_description.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_edit_description.setObjectName("txt_edit_description")
        self.label_availible = QtWidgets.QLabel(widget)
        self.label_availible.setGeometry(QtCore.QRect(10, 450, 111, 31))
        self.label_availible.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "font: 87 16pt \"Segoe UI Black\";")
        self.label_availible.setObjectName("label_availible")
        self.lbl_available = QtWidgets.QLabel(widget)
        self.lbl_available.setGeometry(QtCore.QRect(120, 450, 421, 31))
        self.lbl_available.setStyleSheet("color: rgb(255, 85, 0);\n"
                                         "font: 10pt \"Segoe UI\";")
        self.lbl_available.setText("")
        self.lbl_available.setObjectName("lbl_available")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_name_book1.setText(_translate("widget", "Название:"))
        self.label_name_author1.setText(_translate("widget", "Автор:"))
        self.label_name_genre1.setText(_translate("widget", "Жанр:"))
        self.label_id1.setText(_translate("widget", "ID:"))
        self.label_description1.setText(_translate("widget", "Описание:"))
        self.label_year1.setText(_translate("widget", "Год издания:"))
        self.label_availible.setText(_translate("widget", "Наличие:"))
